name: fraudsters
channels:
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - adwaita-icon-theme=48.1=unix_0
  - alsa-lib=1.2.14=hb9d3cd8_0
  - anyio=4.9.0=pyh29332c3_0
  - argon2-cffi=23.1.0=pyhd8ed1ab_1
  - argon2-cffi-bindings=21.2.0=py313h536fd9c_5
  - arrow=1.3.0=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-lru=2.0.5=pyh29332c3_0
  - at-spi2-atk=2.38.0=h0630a04_3
  - at-spi2-core=2.40.3=h0630a04_0
  - atk-1.0=2.38.0=h04ea711_2
  - attrs=25.3.0=pyh71513ae_0
  - babel=2.17.0=pyhd8ed1ab_0
  - beautifulsoup4=4.13.4=pyha770c72_0
  - binutils_impl_linux-64=2.43=h4bf12b8_4
  - binutils_linux-64=2.43=h4852527_4
  - bleach=6.2.0=pyh29332c3_4
  - bleach-with-css=6.2.0=h82add2a_4
  - brotli=1.1.0=hb9d3cd8_2
  - brotli-bin=1.1.0=hb9d3cd8_2
  - brotli-python=1.1.0=py313h46c70d0_2
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.6.15=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.4=h3394656_0
  - catboost=1.2.8=cuda120_py313h5ec372d_104
  - certifi=2025.6.15=pyhd8ed1ab_0
  - cffi=1.17.1=py313hfab6e84_0
  - charset-normalizer=3.4.2=pyhd8ed1ab_0
  - comm=0.2.2=pyhd8ed1ab_1
  - contourpy=1.3.2=py313h33d0bda_0
  - cuda=12.9.0=0
  - cuda-cccl_linux-64=12.9.27=0
  - cuda-command-line-tools=12.9.0=0
  - cuda-compiler=12.9.0=0
  - cuda-crt-dev_linux-64=12.9.41=0
  - cuda-crt-tools=12.9.41=0
  - cuda-cudart=12.9.37=0
  - cuda-cudart-dev=12.9.37=0
  - cuda-cudart-dev_linux-64=12.9.37=0
  - cuda-cudart-static=12.9.37=0
  - cuda-cudart-static_linux-64=12.9.37=0
  - cuda-cudart_linux-64=12.9.37=0
  - cuda-cuobjdump=12.9.26=1
  - cuda-cupti=12.9.19=0
  - cuda-cupti-dev=12.9.19=0
  - cuda-cuxxfilt=12.9.19=1
  - cuda-driver-dev=12.9.37=0
  - cuda-driver-dev_linux-64=12.9.37=0
  - cuda-gdb=12.9.19=1
  - cuda-libraries=12.9.0=0
  - cuda-libraries-dev=12.9.0=0
  - cuda-nsight=12.9.19=0
  - cuda-nvcc=12.9.41=0
  - cuda-nvcc-dev_linux-64=12.9.41=0
  - cuda-nvcc-impl=12.9.41=0
  - cuda-nvcc-tools=12.9.41=0
  - cuda-nvcc_linux-64=12.9.41=0
  - cuda-nvdisasm=12.9.19=1
  - cuda-nvml-dev=12.9.40=1
  - cuda-nvprof=12.9.19=0
  - cuda-nvprune=12.9.19=1
  - cuda-nvrtc=12.9.41=0
  - cuda-nvrtc-dev=12.9.41=0
  - cuda-nvtx=12.9.19=0
  - cuda-nvvm-dev_linux-64=12.9.41=0
  - cuda-nvvm-impl=12.9.41=0
  - cuda-nvvm-tools=12.9.41=0
  - cuda-nvvp=12.9.19=1
  - cuda-opencl=12.9.19=0
  - cuda-opencl-dev=12.9.19=0
  - cuda-profiler-api=12.9.19=0
  - cuda-runtime=12.9.0=0
  - cuda-sanitizer-api=12.9.27=1
  - cuda-toolkit=12.9.0=0
  - cuda-tools=12.9.0=0
  - cuda-version=12.9=3
  - cuda-visual-tools=12.9.0=0
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.27=h54b06d7_7
  - dbus=1.16.2=h3c4dab8_0
  - debugpy=1.8.14=py313h46c70d0_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - double-conversion=3.3.1=h5888daf_0
  - epoxy=1.5.10=h166bdaf_1
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - expat=2.7.0=h5888daf_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.58.0=py313h8060acc_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freetype=2.13.3=ha770c72_1
  - fribidi=1.0.10=h36c2ea0_0
  - gcc_impl_linux-64=13.3.0=h1e990d8_2
  - gcc_linux-64=13.3.0=hc28eda2_10
  - gdk-pixbuf=2.42.12=hb9ae30d_0
  - gds-tools=1.14.0.30=4
  - glib-tools=2.84.2=h4833e2c_0
  - gmp=6.3.0=hac33072_2
  - graphite2=1.3.13=h59595ed_1003
  - graphviz=13.0.1=hcae58fd_0
  - gtk3=3.24.43=h0c6a113_5
  - gts=0.7.6=h977cf35_4
  - gxx_impl_linux-64=13.3.0=hae580e1_2
  - gxx_linux-64=13.3.0=h6834431_10
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.2.0=pyhd8ed1ab_0
  - harfbuzz=11.2.1=h3beb420_0
  - hicolor-icon-theme=0.17=ha770c72_2
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.6.1=pyha770c72_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=9.2.0=pyhfb0248b_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - ipywidgets=8.1.7=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.0=pyhd8ed1ab_0
  - json5=0.12.0=pyhd8ed1ab_0
  - jsonpointer=3.0.0=py313h78bf25f_1
  - jsonschema=4.23.0=pyhd8ed1ab_1
  - jsonschema-specifications=2025.4.1=pyh29332c3_0
  - jsonschema-with-format-nongpl=4.23.0=hd8ed1ab_1
  - jupyter=1.1.1=pyhd8ed1ab_1
  - jupyter-lsp=2.2.5=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_console=6.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh31011fe_1
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.16.0=pyhe01879c_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.4.2=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.27.3=pyhd8ed1ab_1
  - jupyterlab_widgets=3.0.15=pyhd8ed1ab_0
  - kernel-headers_linux-64=3.10.0=he073ed8_18
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.7=py313h33d0bda_0
  - krb5=1.21.3=h659f571_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.43=h712a8e2_4
  - lerc=4.0.0=h0aef613_1
  - libblas=3.9.0=31_h59b9bed_openblas
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libcblas=3.9.0=31_he106b2a_openblas
  - libclang-cpp20.1=20.1.5=default_h1df26ce_1
  - libclang13=20.1.5=default_he06ed0a_1
  - libcublas=12.9.0.13=0
  - libcublas-dev=12.9.0.13=0
  - libcufft=11.4.0.6=0
  - libcufft-dev=11.4.0.6=0
  - libcufile=1.14.0.30=4
  - libcufile-dev=1.14.0.30=4
  - libcups=2.3.3=h4637d8d_4
  - libcurand=10.3.10.19=0
  - libcurand-dev=10.3.10.19=0
  - libcusolver=11.7.4.40=0
  - libcusolver-dev=11.7.4.40=0
  - libcusparse=12.5.9.5=0
  - libcusparse-dev=12.5.9.5=0
  - libdeflate=1.24=h86f0d12_0
  - libdrm=2.4.124=hb9d3cd8_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.4.6=h2dba641_1
  - libfreetype=2.13.3=ha770c72_1
  - libfreetype6=2.13.3=h48d6fc4_1
  - libgcc=15.1.0=h767d61c_2
  - libgcc-devel_linux-64=13.3.0=hc03c837_102
  - libgcc-ng=15.1.0=h69a702a_2
  - libgd=2.3.3=h6f5c62b_11
  - libgfortran=15.1.0=h69a702a_2
  - libgfortran5=15.1.0=hcea5267_2
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.84.2=h3618099_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.1.0=h767d61c_2
  - libiconv=1.18=h4ce23a2_1
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - liblapack=3.9.0=31_h7ac8fdf_openblas
  - liblightgbm=4.6.0=cuda_h3896ea8_2
  - libllvm20=20.1.5=he9d0ab4_0
  - liblzma=5.8.1=hb9d3cd8_1
  - liblzma-devel=5.8.1=hb9d3cd8_1
  - libmpdec=4.0.0=h4bc722e_0
  - libnpp=12.4.0.27=0
  - libnpp-dev=12.4.0.27=0
  - libntlm=1.8=hb9d3cd8_0
  - libnvfatbin=12.9.19=0
  - libnvfatbin-dev=12.9.19=0
  - libnvjitlink=12.9.41=0
  - libnvjitlink-dev=12.9.41=0
  - libnvjpeg=12.4.0.16=0
  - libnvjpeg-dev=12.4.0.16=0
  - libopenblas=0.3.29=pthreads_h94d23a6_0
  - libopengl=1.7.0=ha4b6fd6_2
  - libpciaccess=0.18=hd590300_0
  - libpng=1.6.47=h943b412_0
  - libpq=17.5=h27ae623_0
  - librsvg=2.58.4=he92a37e_3
  - libsanitizer=13.3.0=he8ea267_2
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.49.2=hee588c1_0
  - libstdcxx=15.1.0=h8f9b012_2
  - libstdcxx-devel_linux-64=13.3.0=hc03c837_102
  - libstdcxx-ng=15.1.0=h4852527_2
  - libtiff=4.7.0=hf01ce69_5
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.17.0=h8a09558_0
  - libxgboost=3.0.2=cuda128_hacb7753_0
  - libxkbcommon=1.9.2=h65c71a3_0
  - libxml2=2.13.8=h4bc477f_0
  - libxslt=1.1.39=h76b75d6_0
  - libzlib=1.3.1=hb9d3cd8_2
  - lightgbm=4.6.0=cuda_py_2
  - markupsafe=3.0.2=py313h8060acc_1
  - matplotlib=3.10.3=py313h78bf25f_0
  - matplotlib-base=3.10.3=py313h129903b_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mistune=3.1.3=pyh29332c3_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - narwhals=1.44.0=pyhe01879c_0
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=pyh29332c3_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - nccl=2.26.6.1=ha44e49d_0
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - notebook=7.4.2=pyhd8ed1ab_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - nsight-compute=2025.2.0.11=0
  - nspr=4.36=h5888daf_0
  - nss=3.112=h159eef7_0
  - numpy=2.2.6=py313h17eae1a_0
  - ocl-icd=2.3.3=hb9d3cd8_0
  - opencl-headers=2024.10.24=h5888daf_0
  - openjpeg=2.5.3=h5fbd93e_0
  - openldap=2.6.9=he970967_0
  - openssl=3.5.0=h7b32b05_1
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=25.0=pyh29332c3_1
  - pandas=2.2.3=py313ha87cce1_3
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - pango=1.56.3=h9ac818e_1
  - parso=0.8.4=pyhd8ed1ab_1
  - patsy=1.0.1=pyhd8ed1ab_1
  - pcre2=10.45=hc749103_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.2.1=py313h8db990d_0
  - pip=25.1.1=pyh145f28c_0
  - pixman=0.46.0=h29eaf8c_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_2
  - platformdirs=4.3.8=pyhe01879c_0
  - plotly=6.1.2=pyhd8ed1ab_0
  - prometheus_client=0.22.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - prompt_toolkit=3.0.51=hd8ed1ab_0
  - psutil=7.0.0=py313h536fd9c_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py-xgboost=3.0.2=cuda128_pyh3ef1b53_0
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.1=pyhd8ed1ab_0
  - pyparsing=3.2.3=pyhd8ed1ab_1
  - pyside6=6.9.0=py313h5f61773_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.13.3=hf636f53_101_cp313
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-fastjsonschema=2.21.1=pyhd8ed1ab_0
  - python-graphviz=0.21=pyhbacfb6d_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.13=7_cp313
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.2=py313h8060acc_2
  - pyzmq=26.4.0=py313h8e95178_0
  - qhull=2020.2=h434a139_5
  - qt6-main=6.9.0=h0384650_3
  - readline=8.2=h8c095d6_2
  - referencing=0.36.2=pyh29332c3_0
  - requests=2.32.3=pyhd8ed1ab_1
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rpds-py=0.25.0=py313h4b2b08d_0
  - scikit-learn=1.6.1=py313h8ef605b_0
  - scipy=1.15.2=py313h86fcf2b_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - send2trash=1.8.3=pyh0d859eb_1
  - setuptools=80.1.0=pyhff2d567_0
  - six=1.17.0=pyhd8ed1ab_0
  - sniffio=1.3.1=pyhd8ed1ab_1
  - soupsieve=2.7=pyhd8ed1ab_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.4=py313ha014f3b_0
  - sysroot_linux-64=2.17=h0157908_18
  - terminado=0.18.1=pyh0d859eb_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - tomli=2.2.1=pyhd8ed1ab_1
  - tornado=6.5=py313h536fd9c_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - types-python-dateutil=2.9.0.20250516=pyhd8ed1ab_0
  - typing-extensions=4.13.2=h0e9735f_0
  - typing_extensions=4.13.2=pyh29332c3_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025b=h78e105d_0
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=2.4.0=pyhd8ed1ab_0
  - wayland=1.23.1=h3e06ad9_1
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - webcolors=24.11.1=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.8.0=pyhd8ed1ab_1
  - widgetsnbextension=4.0.14=pyhd8ed1ab_0
  - xcb-util=0.4.1=hb711507_2
  - xcb-util-cursor=0.1.5=hb9d3cd8_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.44=hb9d3cd8_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxinerama=1.1.5=h5888daf_1
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - xz=5.8.1=hbcc6ac9_1
  - xz-gpl-tools=5.8.1=hbcc6ac9_1
  - xz-tools=5.8.1=hb9d3cd8_1
  - yaml=0.2.5=h7f98852_2
  - zeromq=4.3.5=h3b0a872_7
  - zipp=3.21.0=pyhd8ed1ab_1
  - zstandard=0.23.0=py313h536fd9c_2
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - finding-fraudsters==0.1
prefix: /home/alex/miniconda3/envs/fraudsters
